repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.2.0'
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/codespell-project/codespell
    rev: 'v2.1.0'
    hooks:
    - id: codespell
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.31.1
  hooks:
  - id: markdownlint
